version: '3'

services:
  PW2-mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: PW2-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    volumes:
      - "./app/docker-scripts/sql:/docker-entrypoint-initdb.d"

  PW2-php:
    image: php:${PHP_VERSION}
    container_name: PW2-php
    expose:
      - 80
      - 443
    ports:
      - "${PHP_PORT}:80"
      - "${PHP_SECURE_PORT}:443"
    volumes:
      - ./app/:/var/www/html
    links:
      - PW2-mysql
    command: sh ./docker-scripts/docker-php.sh
