insert into noticia (titulo, contenido, id_seccion, id_contenidista, id_estado, image_path, estado_registro) 
values ("primer titulo", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", 1, 1, 3, "/view/img/asd.jpg", 1),
("segundo titulo", "Pellentesque nec nisi id sapien gravida aliquam nec in ante. Praesent id scelerisque dui, sed pellentesque mauris. Pellentesque libero arcu, sollicitudin quis suscipit sit amet, efficitur luctus lectus. Morbi ultrices accumsan lacus, ut tempor mi cursus sed. Fusce commodo mattis tincidunt. Vestibulum bibendum ipsum at enim venenatis dapibus. Maecenas vitae finibus odio. Pellentesque in finibus ipsum, sed mollis nibh. Aliquam erat volutpat. Donec non lacinia felis, ut vestibulum enim.", 2, 1, 3, "/view/img/asd.jpg", 1),
("tercer titulo", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at pharetra ex. Nam neque dolor, bibendum non ornare at, molestie a ante. Proin porttitor malesuada dictum. Nulla sed sem sapien. Vivamus vitae leo quis purus lacinia bibendum auctor in sem. Nulla et urna quis libero pharetra accumsan. Praesent sollicitudin auctor neque, sit amet convallis lacus molestie non. Etiam consequat sem non mi fringilla, eget malesuada est iaculis. Ut mi nisi, vestibulum eu auctor ac, pharetra eget augue. Aliquam varius mi sit amet nibh semper blandit. Etiam vitae urna pharetra, malesuada ante vel, facilisis nisl. Proin vel consequat arcu.", 3, 1, 3, "/view/img/asd.jpg", 1),
("cuarto titulo", "Aliquam vitae viverra diam. Aenean id ligula mauris. Integer erat est, viverra at condimentum vel, cursus in nunc. Donec dapibus elit sit amet elit auctor, ut fringilla enim convallis. In hac habitasse platea dictumst. Nunc quis ipsum ac lorem lacinia volutpat. Nam non leo nec purus viverra volutpat. Morbi sed diam sapien. Phasellus ut consectetur erat, congue aliquam augue. Ut feugiat massa ut libero tempus aliquam.", 4, 1, 3, "/view/img/asd.jpg", 1),
("Quinto titulo", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis nulla magna. Etiam vitae leo erat. Donec ullamcorper fermentum dui. Phasellus finibus ullamcorper nisi. Suspendisse at turpis orci. Integer vestibulum mauris sed euismod imperdiet. Morbi mattis in eros sed eleifend. Suspendisse eu urna tristique, cursus risus vel, venenatis ligula. Sed feugiat, metus in molestie tristique, sem lectus bibendum orci, nec varius mauris purus a dui.", 5, 1, 3, "/view/img/asd.jpg", 1),
("Sexto titulo", "Etiam tincidunt semper dignissim. Morbi justo est, malesuada non maximus eu, convallis non enim. Proin ac ipsum id eros fermentum congue aliquam eget nulla. Nunc sed elit ullamcorper, malesuada nulla sit amet, tincidunt metus. Donec tempor semper eros vel bibendum. Quisque in hendrerit ex, at vehicula nibh. Quisque sollicitudin, magna ac condimentum vulputate, ipsum velit interdum lorem, sit amet maximus augue mi quis diam.", 6, 1, 3, "/view/img/asd.jpg", 1),
("Septimo titulo", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut hendrerit, ipsum ut porta laoreet, ex nisi tincidunt libero, eget luctus neque lectus in nibh. Mauris eget risus pulvinar, varius lacus sit amet, malesuada purus. Vivamus mattis eros sit amet dapibus dapibus. Mauris elementum eros non mi congue, vitae venenatis massa venenatis. Etiam sit amet quam vel ligula maximus vulputate eu et urna. Curabitur euismod ultrices neque, ac sodales nunc auctor ut.  Ut ullamcorper elit tortor, id commodo ligula laoreet nec. Aliquam euismod, tellus sit amet cursus rutrum, tellus nisl iaculis sem, quis accumsan justo est nec ante.", 2, 1, 3, "/view/img/asd.jpg", 1),
("Octavo titulo", "Maecenas justo ligula, pretium vitae auctor feugiat, ultricies id arcu. Sed porttitor lacus fermentum augue molestie, non lobortis orci tincidunt. Integer mattis diam eget est imperdiet mollis. Quisque sed dolor eget lorem suscipit posuere. Nullam eget ornare dolor, ut pharetra nulla. Vivamus orci est, tincidunt at felis at, scelerisque consequat quam. Mauris eu risus in neque tempus bibendum nec sed nisl. Quisque pulvinar rutrum nibh, non porttitor neque maximus vitae.", 3, 1, 3, "/view/img/asd.jpg", 1);
                
                